logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG

wechat:
  mp:
    appId: wx3e84fd1d502ebb14
    secret: 2e7cb08504fea52aacba2146bf8782ea
    token: weixinmp
    aesKey: weixinmp

spring:
    datasource:
        name: zsedu
        url: jdbc:mysql://rm-wz9n4gn94d28s3393o.mysql.rds.aliyuncs.com/zsedu
        username: root
        password: Xiaohong2b
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.zhishujiaoyu.mapper
    xmlLocation: classpath:mapper/**/*.xml

swagger:
    basepackage: com.zhishujiaoyu.controller
    service:
        name: 知塾教育微信平台
        description:  null
        developer: vayci